# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: ReasoningEngineIAMPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/reasoningengineiampolicy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    policyData: ${data.google_iam_policy.admin.policy_data}
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: reasoning_engine
    reasoningEngineSelector:
      matchLabels:
        testing.upbound.io/example-name: reasoning_engine
    regionSelector:
      matchLabels:
        testing.upbound.io/example-name: reasoning_engine
