# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: iam.gcp.upbound.io/v1beta1
kind: OAuthClientCredential
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/oauthclientcredential
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    disabled: true
    displayName: Display Name of credential
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: oauth_client
    oauthclientSelector:
      matchLabels:
        testing.upbound.io/example-name: oauth_client

---

apiVersion: iam.gcp.upbound.io/v1beta1
kind: OAuthClient
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/oauthclientcredential
  labels:
    testing.upbound.io/example-name: oauth_client
  name: oauth-client
spec:
  forProvider:
    allowedGrantTypes:
    - AUTHORIZATION_CODE_GRANT
    allowedRedirectUris:
    - https://www.example.com
    allowedScopes:
    - https://www.googleapis.com/auth/cloud-platform
    clientType: CONFIDENTIAL_CLIENT
    location: global
