# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cloudrun.gcp.upbound.io/v1beta1
kind: V2JobIAMPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: cloudrun/v1beta1/v2jobiampolicy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    nameSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    policyData: ${data.google_iam_policy.admin.policy_data}
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: default
