# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

version: "2"

run:
  timeout: 90m

output:
  show-stats: true

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
      - github.com/upbound/provider-gcp

linters:
  default: none
  enable:
    - govet
    - gocyclo
    - gocritic
    - goconst
    - revive
    - staticcheck
    - unconvert
    - unused
    - misspell
    - nakedret

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - io/ioutil.ReadFile
        - io/ioutil.ReadDir
        - io/ioutil.ReadAll

    govet:
      disable:
        - shadow

    revive:
      confidence: 0.8

    gocyclo:
      min-complexity: 10

    dupl:
      threshold: 100

    goconst:
      min-len: 3
      min-occurrences: 5

    lll:
      tab-width: 1

    unparam:
      check-exported: false

    nakedret:
      max-func-lines: 30

    gocritic:
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test(ing)?\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - unparam

      - path: _test\.go
        text: "(unnamedResult|exitAfterDefer)"
        linters:
          - gocritic

      - text: "(hugeParam|rangeValCopy):"
        linters:
          - gocritic

      - text: "SA3000:"
        linters:
          - staticcheck

      - text: "QF1008:"
        linters:
          - staticcheck

      - text: "k8s.io/api/core/v1"
        linters:
          - goimports

      - text: "G101:"
        linters:
          - gosec

      - text: "G104:"
        linters:
          - gosec

issues:
  new: false
  max-issues-per-linter: 0
  max-same-issues: 0