# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cloudrun.gcp.m.upbound.io/v1beta1
kind: V2JobIAMPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: cloudrun/v1beta1/v2jobiampolicy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
  namespace: upbound-system
spec:
  forProvider:
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    nameSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    policyData: |
      {
        "bindings":[
          {
            "members":[
              "serviceAccount:official-provider-testing@official-provider-testing.iam.gserviceaccount.com"
            ],
            "role": "roles/run.invoker"
          }]
      }

---

apiVersion: cloudrun.gcp.m.upbound.io/v1beta1
kind: V2Job
metadata:
  annotations:
    meta.upbound.io/example-id: cloudrun/v1beta1/v2jobiampolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    launchStage: BETA
    location: us-central1
    template:
      template:
        containers:
        - image: us-docker.pkg.dev/cloudrun/container/hello
