# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: sql.gcp.m.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    crossplane.io/external-name: official-provider-testing@official-provider-testing.iam
    meta.upbound.io/example-id: sql/v1beta1/user
  labels:
    testing.upbound.io/example-name: example_iam_user
  name: example-iam-user
  namespace: upbound-system
spec:
  forProvider:
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: example_iam_instance
    type: CLOUD_IAM_SERVICE_ACCOUNT
---
apiVersion: sql.gcp.m.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta1/user
    uptest.upbound.io/pre-delete-hook: ../testhooks/delete-iam-user.sh
  labels:
    testing.upbound.io/example-name: example_iam_instance
  name: example-iam-instance-${Rand.RFC1123Subdomain}
  namespace: upbound-system
spec:
  forProvider:
    databaseVersion: POSTGRES_15
    deletionProtection: false
    region: us-central1
    settings:
      databaseFlags:
      - name: cloudsql.iam_authentication
        value: "on"
      diskSize: 20
      edition: ENTERPRISE
      tier: db-f1-micro
