// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

package cluster

import (
	"github.com/upbound/provider-gcp/config/cluster/accessapproval"
	"github.com/upbound/provider-gcp/config/cluster/accesscontextmanager"
	"github.com/upbound/provider-gcp/config/cluster/apigee"
	"github.com/upbound/provider-gcp/config/cluster/beyondcorp"
	"github.com/upbound/provider-gcp/config/cluster/bigquery"
	"github.com/upbound/provider-gcp/config/cluster/bigtable"
	composer "github.com/upbound/provider-gcp/config/cluster/cloudcomposer"
	"github.com/upbound/provider-gcp/config/cluster/cloudfunctions"
	"github.com/upbound/provider-gcp/config/cluster/cloudplatform"
	"github.com/upbound/provider-gcp/config/cluster/cloudrun"
	"github.com/upbound/provider-gcp/config/cluster/cloudscheduler"
	"github.com/upbound/provider-gcp/config/cluster/cloudtasks"
	"github.com/upbound/provider-gcp/config/cluster/compute"
	"github.com/upbound/provider-gcp/config/cluster/container"
	"github.com/upbound/provider-gcp/config/cluster/containerattached"
	"github.com/upbound/provider-gcp/config/cluster/containeraws"
	"github.com/upbound/provider-gcp/config/cluster/containerazure"
	"github.com/upbound/provider-gcp/config/cluster/dataflow"
	"github.com/upbound/provider-gcp/config/cluster/dataplex"
	"github.com/upbound/provider-gcp/config/cluster/dataproc"
	"github.com/upbound/provider-gcp/config/cluster/dns"
	"github.com/upbound/provider-gcp/config/cluster/endpoints"
	"github.com/upbound/provider-gcp/config/cluster/firebaserules"
	"github.com/upbound/provider-gcp/config/cluster/gameservices"
	"github.com/upbound/provider-gcp/config/cluster/gkehub"
	"github.com/upbound/provider-gcp/config/cluster/healthcare"
	"github.com/upbound/provider-gcp/config/cluster/iap"
	"github.com/upbound/provider-gcp/config/cluster/identityplatform"
	"github.com/upbound/provider-gcp/config/cluster/kms"
	"github.com/upbound/provider-gcp/config/cluster/logging"
	"github.com/upbound/provider-gcp/config/cluster/monitoring"
	"github.com/upbound/provider-gcp/config/cluster/networksecurity"
	"github.com/upbound/provider-gcp/config/cluster/notebooks"
	"github.com/upbound/provider-gcp/config/cluster/oslogin"
	"github.com/upbound/provider-gcp/config/cluster/privateca"
	"github.com/upbound/provider-gcp/config/cluster/project"
	"github.com/upbound/provider-gcp/config/cluster/pubsub"
	"github.com/upbound/provider-gcp/config/cluster/redis"
	"github.com/upbound/provider-gcp/config/cluster/secretmanager"
	"github.com/upbound/provider-gcp/config/cluster/servicenetworking"
	"github.com/upbound/provider-gcp/config/cluster/sourcerepo"
	"github.com/upbound/provider-gcp/config/cluster/spanner"
	"github.com/upbound/provider-gcp/config/cluster/sql"
	"github.com/upbound/provider-gcp/config/cluster/storage"
	"github.com/upbound/provider-gcp/config/cluster/tags"
	"github.com/upbound/provider-gcp/config/cluster/tpu"
	"github.com/upbound/provider-gcp/config/cluster/vertexai"
	"github.com/upbound/provider-gcp/config/cluster/vpcaccess"
)

func init() {
	ProviderConfiguration.AddConfig(accessapproval.Configure)
	ProviderConfiguration.AddConfig(accesscontextmanager.Configure)
	ProviderConfiguration.AddConfig(apigee.Configure)
	ProviderConfiguration.AddConfig(bigtable.Configure)
	ProviderConfiguration.AddConfig(composer.Configure)
	ProviderConfiguration.AddConfig(cloudfunctions.Configure)
	ProviderConfiguration.AddConfig(cloudplatform.Configure)
	ProviderConfiguration.AddConfig(cloudrun.Configure)
	ProviderConfiguration.AddConfig(cloudscheduler.Configure)
	ProviderConfiguration.AddConfig(cloudtasks.Configure)
	ProviderConfiguration.AddConfig(containerattached.Configure)
	ProviderConfiguration.AddConfig(containeraws.Configure)
	ProviderConfiguration.AddConfig(containerazure.Configure)
	ProviderConfiguration.AddConfig(compute.Configure)
	ProviderConfiguration.AddConfig(container.Configure)
	ProviderConfiguration.AddConfig(dataflow.Configure)
	ProviderConfiguration.AddConfig(dataplex.Configure)
	ProviderConfiguration.AddConfig(dataproc.Configure)
	ProviderConfiguration.AddConfig(dns.Configure)
	ProviderConfiguration.AddConfig(endpoints.Configure)
	ProviderConfiguration.AddConfig(firebaserules.Configure)
	ProviderConfiguration.AddConfig(gameservices.Configure)
	ProviderConfiguration.AddConfig(iap.Configure)
	ProviderConfiguration.AddConfig(identityplatform.Configure)
	ProviderConfiguration.AddConfig(logging.Configure)
	ProviderConfiguration.AddConfig(kms.Configure)
	ProviderConfiguration.AddConfig(networksecurity.Configure)
	ProviderConfiguration.AddConfig(notebooks.Configure)
	ProviderConfiguration.AddConfig(privateca.Configure)
	ProviderConfiguration.AddConfig(oslogin.Configure)
	ProviderConfiguration.AddConfig(project.Configure)
	ProviderConfiguration.AddConfig(pubsub.Configure)
	ProviderConfiguration.AddConfig(redis.Configure)
	ProviderConfiguration.AddConfig(secretmanager.Configure)
	ProviderConfiguration.AddConfig(servicenetworking.Configure)
	ProviderConfiguration.AddConfig(sourcerepo.Configure)
	ProviderConfiguration.AddConfig(spanner.Configure)
	ProviderConfiguration.AddConfig(storage.Configure)
	ProviderConfiguration.AddConfig(sql.Configure)
	ProviderConfiguration.AddConfig(redis.Configure)
	ProviderConfiguration.AddConfig(bigquery.Configure)
	ProviderConfiguration.AddConfig(beyondcorp.Configure)
	ProviderConfiguration.AddConfig(vertexai.Configure)
	ProviderConfiguration.AddConfig(tags.Configure)
	ProviderConfiguration.AddConfig(tpu.Configure)
	ProviderConfiguration.AddConfig(vpcaccess.Configure)
	ProviderConfiguration.AddConfig(healthcare.Configure)
	ProviderConfiguration.AddConfig(gkehub.Configure)
	ProviderConfiguration.AddConfig(monitoring.Configure)
}
