# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: managed.gcp.m.upbound.io/v1beta1
kind: KafkaACL
metadata:
  annotations:
    crossplane.io/external-name: "topic/example1"
  name: example1
  namespace: default
spec:
  forProvider:
    cluster: my-cluster
    aclId: "topic/example1"
    aclEntries:
    - host: '*'
      operation: ALL
      permissionType: ALLOW
      principal: User:sa
    location: europe-north1
  providerConfigRef:
    name: default
    kind: ProviderConfig