/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	v1beta1 "github.com/upbound/provider-gcp/apis/cloudfunctions2/v1beta1"
	resource "github.com/upbound/upjet/pkg/resource"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Group.
func (mg *Group) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ParentName),
		Extract:      resource.ExtractParamPath("name", true),
		Reference:    mg.Spec.ForProvider.ParentNameRef,
		Selector:     mg.Spec.ForProvider.ParentNameSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ParentName")
	}
	mg.Spec.ForProvider.ParentName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SLO.
func (mg *SLO) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Service),
		Extract:      resource.ExtractParamPath("service_id", false),
		Reference:    mg.Spec.ForProvider.ServiceRef,
		Selector:     mg.Spec.ForProvider.ServiceSelector,
		To: reference.To{
			List:    &CustomServiceList{},
			Managed: &CustomService{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Service")
	}
	mg.Spec.ForProvider.Service = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServiceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this UptimeCheckConfig.
func (mg *UptimeCheckConfig) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.ResourceGroup); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ResourceGroup[i3].GroupID),
			Extract:      resource.ExtractParamPath("name", true),
			Reference:    mg.Spec.ForProvider.ResourceGroup[i3].GroupIDRef,
			Selector:     mg.Spec.ForProvider.ResourceGroup[i3].GroupIDSelector,
			To: reference.To{
				List:    &GroupList{},
				Managed: &Group{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ResourceGroup[i3].GroupID")
		}
		mg.Spec.ForProvider.ResourceGroup[i3].GroupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ResourceGroup[i3].GroupIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.SyntheticMonitor); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.SyntheticMonitor[i3].CloudFunctionV2); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SyntheticMonitor[i3].CloudFunctionV2[i4].Name),
				Extract:      resource.ExtractResourceID(),
				Reference:    mg.Spec.ForProvider.SyntheticMonitor[i3].CloudFunctionV2[i4].NameRef,
				Selector:     mg.Spec.ForProvider.SyntheticMonitor[i3].CloudFunctionV2[i4].NameSelector,
				To: reference.To{
					List:    &v1beta1.FunctionList{},
					Managed: &v1beta1.Function{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.SyntheticMonitor[i3].CloudFunctionV2[i4].Name")
			}
			mg.Spec.ForProvider.SyntheticMonitor[i3].CloudFunctionV2[i4].Name = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.SyntheticMonitor[i3].CloudFunctionV2[i4].NameRef = rsp.ResolvedReference

		}
	}

	return nil
}
