# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: storagetransfer.gcp.upbound.io/v1beta1
kind: Job
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: gcs-bucket-nightly-backup
  name: gcs-bucket-nightly-backup
spec:
  forProvider:
    description: Nightly backup of GCS bucket
    loggingConfig:
      logActionStates:
      - SUCCEEDED
      - FAILED
      logActions:
      - COPY
      - DELETE
    notificationConfig:
      eventTypes:
      - TRANSFER_OPERATION_SUCCESS
      - TRANSFER_OPERATION_FAILED
      payloadFormat: JSON
      pubsubTopicSelector:
        matchLabels:
          testing.upbound.io/example-name: topic
    project: ${var.project}
    schedule:
      repeatInterval: 604800s
      scheduleEndDate:
        day: 15
        month: 1
        year: 2019
      scheduleStartDate:
        day: 1
        month: 10
        year: 2018
      startTimeOfDay:
        hours: 23
        minutes: 30
        nanos: 0
        seconds: 0
    transferSpec:
      gcsDataSource:
        bucketName: source-bucket-${Rand.RFC1123Subdomain}
      gcsDataSink:
        bucketNameSelector:
          matchLabels:
            testing.upbound.io/example-name: s3-backup-bucket
        path: foo/bar/
      objectConditions:
        excludePrefixes:
        - requests.gz
        maxTimeElapsedSinceLastModification: 600s
      transferOptions:
        deleteObjectsUniqueInSink: false

---

apiVersion: pubsub.gcp.upbound.io/v1beta2
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: topic
  name: topic
spec:
  forProvider: {}

---

apiVersion: storage.gcp.upbound.io/v1beta2
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: source-bucket
  name: source-bucket-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    location: US
    storageClass: NEARLINE

---

apiVersion: storage.gcp.upbound.io/v1beta2
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: gcs-backup-bucket
  name: gcs-backup-bucket-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    location: US
    storageClass: NEARLINE
