# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: networksecurity.gcp.upbound.io/v1beta1
kind: ClientTLSPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: networksecurity/v1beta1/clienttlspolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    clientCertificate:
      certificateProviderInstance:
        pluginInstance: google_cloud_private_spiffe
    description: my description
    labels:
      foo: bar
    location: global
    serverValidationCa:
    - grpcEndpoint:
        targetUri: unix:mypath
    sni: secure.example.com
