# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cloudidentity.gcp.upbound.io/v1beta1
kind: GroupMembership
metadata:
  annotations:
    meta.upbound.io/example-id: cloudidentity/v1beta1/groupmembership
    upjet.upbound.io/manual-intervention: "Requires a real organization related customer id and domain"
  labels:
    testing.upbound.io/example-name: cloud_identity_group_membership_basic
  name: cloud-identity-group-membership-basic
spec:
  forProvider:
    groupSelector:
      matchLabels:
        testing.upbound.io/example-name: child-group
    preferredMemberKey:
      id: my-identity-group-test@<real-domain-for-organization>
    roles:
    - name: MEMBER

---

apiVersion: cloudidentity.gcp.upbound.io/v1beta1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: cloudidentity/v1beta1/groupmembership
    upjet.upbound.io/manual-intervention: "Requires a real organization related customer id and domain"
  labels:
    testing.upbound.io/example-name: child-group
  name: child-group
spec:
  forProvider:
    displayName: my-identity-group
    groupKey:
      id: my-identity-group-test@<real-domain-for-organization>
    initialGroupConfig: WITH_INITIAL_OWNER
    labels:
      cloudidentity.googleapis.com/groups.discussion_forum: ""
    parent: customers/<real_organization_related_customer_id>
