# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: storagetransfer.gcp.m.upbound.io/v1beta1
kind: Job
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: gcs-bucket-nightly-backup
  name: gcs-bucket-nightly-backup
  namespace: upbound-system
spec:
  forProvider:
    description: Nightly backup of GCS bucket
    loggingConfig:
      logActionStates:
      - SUCCEEDED
      - FAILED
      logActions:
      - COPY
      - DELETE
    notificationConfig:
      eventTypes:
      - TRANSFER_OPERATION_SUCCESS
      - TRANSFER_OPERATION_FAILED
      payloadFormat: JSON
      pubsubTopicSelector:
        matchLabels:
          testing.upbound.io/example-name: topic
    schedule:
      repeatInterval: 604800s
      scheduleEndDate:
        day: 15
        month: 1
        year: 2019
      scheduleStartDate:
        day: 1
        month: 10
        year: 2018
      startTimeOfDay:
        hours: 23
        minutes: 30
        nanos: 0
        seconds: 0
    transferSpec:
      gcsDataSource:
        bucketNameSelector:
          matchLabels:
            testing.upbound.io/example-name: source-bucket
      gcsDataSink:
        bucketNameSelector:
          matchLabels:
            testing.upbound.io/example-name: backup-bucket
        path: foo/bar/
      objectConditions:
        excludePrefixes:
        - requests.gz
        maxTimeElapsedSinceLastModification: 600s
      transferOptions:
        deleteObjectsUniqueInSink: false

---

apiVersion: pubsub.gcp.m.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: topic
  name: topic
  namespace: upbound-system
spec:
  forProvider: {}

---

apiVersion: storage.gcp.m.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: source-bucket
  name: source-bucket-${Rand.RFC1123Subdomain}
  namespace: upbound-system
spec:
  forProvider:
    location: US
    storageClass: NEARLINE

---

apiVersion: storage.gcp.m.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: backup-bucket
  name: backup-bucket-${Rand.RFC1123Subdomain}
  namespace: upbound-system
spec:
  forProvider:
    location: US
    storageClass: NEARLINE

---


apiVersion: storage.gcp.m.upbound.io/v1beta1
kind: BucketIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: source-bucket-iam-member
  name: source-bucket-iam-member
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: source-bucket
    member: serviceAccount:project-${data.cloudplatform_project.projectNumber}@storage-transfer-service.iam.gserviceaccount.com
    role: roles/storage.admin

---

apiVersion: storage.gcp.m.upbound.io/v1beta1
kind: BucketIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: backup-bucket-iam-member
  name: backup-bucket-iam-member
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: backup-bucket
    member: serviceAccount:project-${data.cloudplatform_project.projectNumber}@storage-transfer-service.iam.gserviceaccount.com
    role: roles/storage.admin

---

apiVersion: pubsub.gcp.m.upbound.io/v1beta1
kind: TopicIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: storagetransfer/v1beta1/job
  labels:
    testing.upbound.io/example-name: topic-iam-member
  name: topic-iam-member
spec:
  forProvider:
    member: serviceAccount:project-${data.cloudplatform_project.projectNumber}@storage-transfer-service.iam.gserviceaccount.com
    role: roles/pubsub.publisher
    topicSelector:
      matchLabels:
        testing.upbound.io/example-name: topic
