// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DenialConditionInitParameters struct {

	// The description of the rule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Textual representation of an expression in Common Expression Language syntax.
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// String indicating the location of the expression for error reporting,
	// e.g. a file name and a position in the file.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Title for the expression, i.e. a short string describing its purpose.
	// This can be used e.g. in UIs which allow to enter the expression.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type DenialConditionObservation struct {

	// The description of the rule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Textual representation of an expression in Common Expression Language syntax.
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// String indicating the location of the expression for error reporting,
	// e.g. a file name and a position in the file.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Title for the expression, i.e. a short string describing its purpose.
	// This can be used e.g. in UIs which allow to enter the expression.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type DenialConditionParameters struct {

	// The description of the rule.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Textual representation of an expression in Common Expression Language syntax.
	// +kubebuilder:validation:Optional
	Expression *string `json:"expression" tf:"expression,omitempty"`

	// String indicating the location of the expression for error reporting,
	// e.g. a file name and a position in the file.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Title for the expression, i.e. a short string describing its purpose.
	// This can be used e.g. in UIs which allow to enter the expression.
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type DenyPolicyInitParameters struct {

	// The display name of the rule.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Rules to be applied.
	// Structure is documented below.
	Rules []RulesInitParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type DenyPolicyObservation struct {

	// Defaults to DELETE.
	// When set to "DELETE", deleting the resource is allowed.
	DeletionPolicy *string `json:"deletionPolicy,omitempty" tf:"deletion_policy,omitempty"`

	// The display name of the rule.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The hash of the resource. Used internally during updates.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	// an identifier for the resource with format {{parent}}/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The attachment point is identified by its URL-encoded full resource name.
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Rules to be applied.
	// Structure is documented below.
	Rules []RulesObservation `json:"rules,omitempty" tf:"rules,omitempty"`
}

type DenyPolicyParameters struct {

	// The display name of the rule.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The attachment point is identified by its URL-encoded full resource name.
	// +kubebuilder:validation:Required
	Parent *string `json:"parent" tf:"parent,omitempty"`

	// Rules to be applied.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	Rules []RulesParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type DenyRuleInitParameters struct {

	// User defined CEVAL expression. A CEVAL expression is used to specify match criteria such as origin.ip, source.region_code and contents in the request header.
	// Structure is documented below.
	DenialCondition *DenialConditionInitParameters `json:"denialCondition,omitempty" tf:"denial_condition,omitempty"`

	// The permissions that are explicitly denied by this rule. Each permission uses the format {service-fqdn}/{resource}.{verb},
	// where {service-fqdn} is the fully qualified domain name for the service. For example, iam.googleapis.com/roles.list.
	DeniedPermissions []*string `json:"deniedPermissions,omitempty" tf:"denied_permissions,omitempty"`

	// The identities that are prevented from using one or more permissions on Google Cloud resources.
	DeniedPrincipals []*string `json:"deniedPrincipals,omitempty" tf:"denied_principals,omitempty"`

	// Specifies the permissions that this rule excludes from the set of denied permissions given by deniedPermissions.
	// If a permission appears in deniedPermissions and in exceptionPermissions then it will not be denied.
	// The excluded permissions can be specified using the same syntax as deniedPermissions.
	ExceptionPermissions []*string `json:"exceptionPermissions,omitempty" tf:"exception_permissions,omitempty"`

	// The identities that are excluded from the deny rule, even if they are listed in the deniedPrincipals.
	// For example, you could add a Google group to the deniedPrincipals, then exclude specific users who belong to that group.
	ExceptionPrincipals []*string `json:"exceptionPrincipals,omitempty" tf:"exception_principals,omitempty"`
}

type DenyRuleObservation struct {

	// User defined CEVAL expression. A CEVAL expression is used to specify match criteria such as origin.ip, source.region_code and contents in the request header.
	// Structure is documented below.
	DenialCondition *DenialConditionObservation `json:"denialCondition,omitempty" tf:"denial_condition,omitempty"`

	// The permissions that are explicitly denied by this rule. Each permission uses the format {service-fqdn}/{resource}.{verb},
	// where {service-fqdn} is the fully qualified domain name for the service. For example, iam.googleapis.com/roles.list.
	DeniedPermissions []*string `json:"deniedPermissions,omitempty" tf:"denied_permissions,omitempty"`

	// The identities that are prevented from using one or more permissions on Google Cloud resources.
	DeniedPrincipals []*string `json:"deniedPrincipals,omitempty" tf:"denied_principals,omitempty"`

	// Specifies the permissions that this rule excludes from the set of denied permissions given by deniedPermissions.
	// If a permission appears in deniedPermissions and in exceptionPermissions then it will not be denied.
	// The excluded permissions can be specified using the same syntax as deniedPermissions.
	ExceptionPermissions []*string `json:"exceptionPermissions,omitempty" tf:"exception_permissions,omitempty"`

	// The identities that are excluded from the deny rule, even if they are listed in the deniedPrincipals.
	// For example, you could add a Google group to the deniedPrincipals, then exclude specific users who belong to that group.
	ExceptionPrincipals []*string `json:"exceptionPrincipals,omitempty" tf:"exception_principals,omitempty"`
}

type DenyRuleParameters struct {

	// User defined CEVAL expression. A CEVAL expression is used to specify match criteria such as origin.ip, source.region_code and contents in the request header.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	DenialCondition *DenialConditionParameters `json:"denialCondition,omitempty" tf:"denial_condition,omitempty"`

	// The permissions that are explicitly denied by this rule. Each permission uses the format {service-fqdn}/{resource}.{verb},
	// where {service-fqdn} is the fully qualified domain name for the service. For example, iam.googleapis.com/roles.list.
	// +kubebuilder:validation:Optional
	DeniedPermissions []*string `json:"deniedPermissions,omitempty" tf:"denied_permissions,omitempty"`

	// The identities that are prevented from using one or more permissions on Google Cloud resources.
	// +kubebuilder:validation:Optional
	DeniedPrincipals []*string `json:"deniedPrincipals,omitempty" tf:"denied_principals,omitempty"`

	// Specifies the permissions that this rule excludes from the set of denied permissions given by deniedPermissions.
	// If a permission appears in deniedPermissions and in exceptionPermissions then it will not be denied.
	// The excluded permissions can be specified using the same syntax as deniedPermissions.
	// +kubebuilder:validation:Optional
	ExceptionPermissions []*string `json:"exceptionPermissions,omitempty" tf:"exception_permissions,omitempty"`

	// The identities that are excluded from the deny rule, even if they are listed in the deniedPrincipals.
	// For example, you could add a Google group to the deniedPrincipals, then exclude specific users who belong to that group.
	// +kubebuilder:validation:Optional
	ExceptionPrincipals []*string `json:"exceptionPrincipals,omitempty" tf:"exception_principals,omitempty"`
}

type RulesInitParameters struct {

	// A deny rule in an IAM deny policy.
	// Structure is documented below.
	DenyRule *DenyRuleInitParameters `json:"denyRule,omitempty" tf:"deny_rule,omitempty"`

	// The description of the rule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`
}

type RulesObservation struct {

	// A deny rule in an IAM deny policy.
	// Structure is documented below.
	DenyRule *DenyRuleObservation `json:"denyRule,omitempty" tf:"deny_rule,omitempty"`

	// The description of the rule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`
}

type RulesParameters struct {

	// A deny rule in an IAM deny policy.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	DenyRule *DenyRuleParameters `json:"denyRule,omitempty" tf:"deny_rule,omitempty"`

	// The description of the rule.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`
}

// DenyPolicySpec defines the desired state of DenyPolicy
type DenyPolicySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   DenyPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DenyPolicyInitParameters `json:"initProvider,omitempty"`
}

// DenyPolicyStatus defines the observed state of DenyPolicy.
type DenyPolicyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DenyPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DenyPolicy is the Schema for the DenyPolicys API. Represents a collection of denial policies to apply to a given resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type DenyPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rules) || (has(self.initProvider) && has(self.initProvider.rules))",message="spec.forProvider.rules is a required parameter"
	Spec   DenyPolicySpec   `json:"spec"`
	Status DenyPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DenyPolicyList contains a list of DenyPolicys
type DenyPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DenyPolicy `json:"items"`
}

// Repository type metadata.
var (
	DenyPolicy_Kind             = "DenyPolicy"
	DenyPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DenyPolicy_Kind}.String()
	DenyPolicy_KindAPIVersion   = DenyPolicy_Kind + "." + CRDGroupVersion.String()
	DenyPolicy_GroupVersionKind = CRDGroupVersion.WithKind(DenyPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&DenyPolicy{}, &DenyPolicyList{})
}
