# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: managed.gcp.upbound.io/v1beta1
kind: KafkaTopic
metadata:
  annotations:
    meta.upbound.io/example-id: managed/v1beta1/kafkatopic
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: cluster
    configs:
      cleanup.policy: compact
    location: us-central1
    partitionCount: 2
    replicationFactor: 3

---

apiVersion: managed.gcp.upbound.io/v1beta1
kind: KafkaCluster
metadata:
  annotations:
    meta.upbound.io/example-id: managed/v1beta1/kafkatopic
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    capacityConfig:
      memoryBytes: 3221225472
      vcpuCount: 3
    gcpConfig:
      accessConfig:
        networkConfigs:
        - subnet: projects/${data.google_project.project.number}/regions/us-central1/subnetworks/default
    location: us-central1
