# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: firestore.gcp.m.upbound.io/v1beta1
kind: Field
metadata:
  annotations:
    meta.upbound.io/example-id: firestore/v1beta1/field
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    collection: chatrooms
    databaseSelector:
      matchLabels:
        testing.upbound.io/example-name: database
    field: basic
    indexConfig:
      indexes:
      - order: ASCENDING
        queryScope: COLLECTION_GROUP
      - arrayConfig: CONTAINS
    project: official-provider-testing

---

apiVersion: firestore.gcp.m.upbound.io/v1beta1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: firestore/v1beta1/field
  labels:
    testing.upbound.io/example-name: database
  name: database
spec:
  forProvider:
    deleteProtectionState: DELETE_PROTECTION_DISABLED
    deletionPolicy: DELETE
    locationId: us-central1
    name: database-id
    project: official-provider-testing
    type: FIRESTORE_NATIVE
