# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: firestore.gcp.m.upbound.io/v1beta1
kind: Index
metadata:
  annotations:
    meta.upbound.io/example-id: firestore/v1beta1/index
  labels:
    testing.upbound.io/example-name: my-index
  name: my-index
spec:
  forProvider:
    collection: atestcollection
    databaseSelector:
      matchLabels:
        testing.upbound.io/example-name: database
    fields:
    - fieldPath: name
      order: ASCENDING
    - fieldPath: description
      order: DESCENDING
    project: official-provider-testing

---

apiVersion: firestore.gcp.m.upbound.io/v1beta1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: firestore/v1beta1/index
  labels:
    testing.upbound.io/example-name: database
  name: database
spec:
  forProvider:
    deleteProtectionState: DELETE_PROTECTION_DISABLED
    deletionPolicy: DELETE
    locationId: us-central1
    name: database-id
    project: official-provider-testing
    type: FIRESTORE_NATIVE
