# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: ReasoningEngine
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/reasoningengine
  labels:
    testing.upbound.io/example-name: reasoning_engine
  name: reasoning-engine
spec:
  forProvider:
    deletionPolicy: FORCE
    displayName: reasoning-engine
    region: us-central1
    spec:
      identityType: AGENT_IDENTITY
